### ISSUE TITLE
Primitive type should be described as not nullable

### ISSUE THREAD

**Issue by m-titov** [ScaCap/spring-auto-restdocs#114]
Subj

**Comment by fbenz** [comment]
Makes sense and should only require a small change.

**Comment by jmisur** [comment]
So I looked at primitive type usage in Spring MVC and Jackson. Again, it's not about what we would like, but what is inherent in the language and frameworks we are using. 
So for path and query parameters, spring doesn't allow missing/null value for primitive types, which is understandable, so they are marked always as mandatory, regardless of `required` field on the annotation.
However for request/response fields, Jackson is responsible for de/serializing and there we must adhere to what it does. We will check `FAIL_ON_NULL_FOR_PRIMITIVES` [deserialization feature](https://github.com/FasterXML/jackson-databind/wiki/Deserialization-Features) to see if null-to-primitive assignment is allowed. Based on that config we'll mark the field as optional or not. Note: by default the feature is not enabled, so they are optional.

**Comment by sebastientromp** [comment]
So this means that primitives are optional or not on a global basis, and we have no control on whether a specific field should be optional or mandatory, right?
I tried several annotations (NotNull, NotBlank, Min, Positive) to see if any one of them could force an individual field to be recognized as mandatory, but to no avail.

Do you know of a solution on a field-by-field basis for this? Or is the only option to use Integer objects instead of primitives?

**Comment by jmisur** [comment]
I don't. From my experience, the best way is to always use wrapper types in MVC and JPA, to prevent any surprises or problems.
