### ISSUE TITLE
Support for JsonProperty.Access

### ISSUE THREAD

**Issue by mvanderlugt** [ScaCap/spring-auto-restdocs#142]
I don't think the documentation is generated quite right when using property access control through Jackson. The property I annotated with WRITE_ONLY access showed up in the generated Response Fields section and READ_ONLY shows up in the Request Fields. Is there a plan to add this functionality in the near future or could you point me in the right direction and I could look at creating a PR for this support?

**Comment by jmisur** [comment]
To rephrase: you want to use 1 class for request and response and have some fields to be write only so they show up only in request section, and some to be read only so they show up only in response section, and everything else show in both?

**Comment by fbenz** [comment]
I looked into it and ran into an issue: `WRITE_ONLY` fields are not visible to our Jackson visitor, because the visitor hooks into the serializer side of Jackson. The starting point for the visitor is `ObjectWriter.acceptJsonFormatVisitor` in `FieldDocumentationGenerator`. As it is not configurable whether the serializer sees `WRITE_ONLY` fields, I don't see an easy way of adding support for `JsonProperty.Access` at the moment.

**Comment by ractive** [comment]
But you could ignore READ_ONLY fields in the JacksonRequestFieldSnippet, isn't it? That would already help a lot.

**Comment by fbenz** [comment]
Yes, that should be possible.

The `JacksonRequestFieldSnippet` would have to pass the information that a request is processed to the `FieldDocumentationGenerator`. The `FieldDocumentationGenerator` is instantiated in the [AbstractJacksonFieldSnippet](https://github.com/ScaCap/spring-auto-restdocs/blob/76af31a11ddb64a5c5dc34fe9eb0808110599a81/spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/payload/AbstractJacksonFieldSnippet.java#L110). This information then can to be used in `FieldDocumentationObjectVisitor` to exclude `READ_ONLY` fields.

**Comment by mvanderlugt** [comment]
That would help a lot, the most common case we have is for primary ids that are read only. Having extra objects just for one field gets unwieldy pretty fast. 

```
{
id: 123,   //<<< read only
email: 'bla@gmail.com',
....
}
```

**Comment by fbenz** [comment]
In my opinion, there is an even better solution than reading the access annotations:
We could compare the actual JSON request/response (dynamic) against the fields extracted by the Jackson visitor (static) and throw out fields that are not part of the actual request/response. Spring REST Docs already does something similar by looking at the actual request/response to determine undocumented fields. This solution should solve all issues around fields that are not actually part of the request/response.

**Comment by mvanderlugt** [comment]
That makes a lot of sense, I'm assuming that the test exercising the endpoint would need to cover all available fields in the request/response for them to show up in the docs?

**Comment by melissapalmer** [comment]
Hi @fbenz , is it already possible to use your suggestion for throwing out fields that are not part of the actual request/response? Do you have an example of how I can do this? Or is this something that would still need to be added? Thanks Melissa

**Comment by fbenz** [comment]
Hi @melissapalmer, this feature does not exist yet. I understand that it's a nice feature to have for cases where the POJOs do not 100% match the request/response, but we have no timeline for adding this feature yet. Contributions are of course welcome.

**Comment by fbenz** [comment]
I see two parts here:
1. Get the content from the request/response
2. Compare the fields

Spring REST Docs has code for both parts, but the code is private and thus can not be reused. However, the code can be used as a blueprint.

1 in Spring REST Docs:
* In [AbstractFieldsSnippet.createModel](https://github.com/spring-projects/spring-restdocs/blob/5ac105db831481fe7b75e9df5d9d118866f4cad5/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/AbstractFieldsSnippet.java#L155) `getContent(operation)` is called. `getContent()` is implemented in the concrete snippets. The same pattern can be used for `AbstractJacksonFieldSnippet` and the implementation  `JacksonRequestFieldSnippet` and `JacksonResponseFieldSnippet` in Spring Auto REST Docs. It makes sense to put the code that gets the actual fields out of the request/response into `JacksonRequestFieldSnippet` and `JacksonResponseFieldSnippet` because this code differs on whether it is a request or a response. `Operation` has the methods `getRequest()` and `getResponse()` (e.g. `Operation.getRequest().getContent()`).

2 in Spring REST Docs:
* [JsonContentHandler](https://github.com/spring-projects/spring-restdocs/blob/660c440c6c971a40610ff5cc4c9ec94aadd28aed/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonContentHandler.java) and [JsonFieldProcessor](https://github.com/spring-projects/spring-restdocs/blob/cfb1fbc85d23335896080a934c3429c5d55d72bc/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonFieldProcessor.java) are used to compare field descriptors against actual fields. Similar code could be added to Spring Auto REST Docs.

Thus, a starting point is [AbstractJacksonFieldSnippet.createFieldDescriptors](https://github.com/ScaCap/spring-auto-restdocs/blob/76af31a11ddb64a5c5dc34fe9eb0808110599a81/spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/payload/AbstractJacksonFieldSnippet.java#L107) where the field descriptors are created and could be compared against the actual fields. The general check is independent on whether it is a request or response and thus makes sense in  `AbstractJacksonFieldSnippet`. Only the request/response dependent code should be put into [JacksonRequestFieldSnippet](https://github.com/ScaCap/spring-auto-restdocs/blob/76af31a11ddb64a5c5dc34fe9eb0808110599a81/spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/payload/JacksonRequestFieldSnippet.java) and [JacksonResponseFieldSnippet](https://github.com/ScaCap/spring-auto-restdocs/blob/76af31a11ddb64a5c5dc34fe9eb0808110599a81/spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/payload/JacksonResponseFieldSnippet.java).

I hope this helps. Let me know if you have further questions.

**Comment by karlmuscat** [comment]
any progress on this issue please?

**Comment by jmisur** [comment]
@karlmuscat @melissapalmer @mvanderlugt this is present in 2.0.9-SNAPSHOT, can one of you please test if it works for you?

**Comment by karlmuscat** [comment]
In what repo can I find the library?

**Comment by jmisur** [comment]
> In what repo can I find the library?

https://scacap.github.io/spring-auto-restdocs/#gettingstarted-snapshot
