### ISSUE TITLE
Allow defining type mapping

### ISSUE THREAD

**Issue by ractive** [ScaCap/spring-auto-restdocs#180]
It would be nice to define your own type mapping. Take this controller method as an example:
```
@GetMapping("/foo")
public String foo(@RequestParam(name="lang", defaultValue="de") Locale locale) { ... }
```
The documentation would label the type of the locale argument as `Object`. But Spring converts a string as an input parameter automatically to a Locale instance. So in the documentation I'd like to have the "lang" parameter being declared as type `String`.

`TypeUtil#getSimpleName` uses `Object` as a fallback for not well known types - which if from a client perspective useless. I was even wondering if the fallback could be `String` for any type, as from a client's point of view, everything is passed in as a String anyway and Spring needs to be able to convert from a String to the `@RequestParam`'s type in all cases.

So either the default type could be String or there's a config setting to allow defining mappings that e.g. document a `Locale` param as type `String`.

**Comment by jmisur** [comment]
Usually Locale is used without annotation, because Spring resolves proper locale from the request (https://docs.spring.io/spring/docs/4.3.13.RELEASE/spring-framework-reference/htmlsingle/#mvc-ann-arguments). In that case we do not document anything. 
Now your Locale is actually custom request parameter and in that case it's an unknown class for us. 
Created #185
