### ISSUE TITLE
Support @PreAuthorize RestController annotations

### ISSUE THREAD

**Issue by mjmeyer** [ScaCap/spring-auto-restdocs#207]
Similar to how JSR303 constraints are handled, would love it if an authorization snippet could be produced from the @PreAuthorize.

Typical usage for me is smth like:
```
@PreAuthorize("hasAnyRole('AGENT','ADMIN')")
    @RequestMapping(method = RequestMethod.DELETE, value = "/api/contract/{id}", produces = "application/json")
    @ResponseBody
    public ResponseEntity<Map<String, Object>> delete(@PathVariable Long id) {...
```

For now I am using the method javadoc to get this info in the description snippet by:
```
/***
     * Deletes a contract.
     * <p>Requires role: [role]#ADMIN# | [role]#AGENT#
     * @title Remove Contract
     * @param id the contract id to remove
     * @return
     */
```

Appreciate the support for `<p>` in the javadoc body and thankfully the asciidoc css class markers (` [role]#...#`) make it across.

**Comment by jmisur** [comment]
PR to enhance auth snippet would be very welcome!

**Comment by jmisur** [comment]
Hi, it's very unlikely that we will pick this up, because security configuration can be done in multiple ways, using these annotations or global security configuration using `HttpSecurity`.
However you can use custom auth in MockMvc tests which contains description for 'AGENT' and 'ADMIN' at the same time, e.g. by creating `agentOrAdminToken` auth request post processor as described in [docs](https://scacap.github.io/spring-auto-restdocs/#snippets-authorization). The documentation output is free text field, and you can put there similar description as you did in Javadoc example above.
