### ISSUE TITLE
Spring HATEOAS support

### ISSUE THREAD

**Issue by viktorgt** [ScaCap/spring-auto-restdocs#246]
Is there a way to get a correct documentation for a HATEOAS resource?

As for example:
```
{
  "id" : "package1",
  "workstationId" : "workstation1",
  "status" : "RELEASED",
  "_embedded" : {
    "pockets" : [ {
      "id" : "1",
      "status" : "ARRIVED",
      "packageId" : "package1",
      "sequence" : 1
    }, {
      "id" : "2",
      "status" : "ARRIVED",
      "packageId" : "package1",
      "sequence" : 2
    }, {
      "id" : "3",
      "status" : "ANNOUNCED",
      "packageId" : "package1",
      "sequence" : null
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/api/packages/package1"
    },
    "packages" : {
      "href" : "http://localhost:8080/api/packages"
    }
  }
}
```

And this is the generated response field documantion by auto-restdocs:
![image](https://user-images.githubusercontent.com/484128/42744403-a5cfa7ee-88cc-11e8-8d39-31d3e2ea6b1f.png)

After having a look into the code of spring-auto-restdocs I see some ways to get rid of the links and to generate a seperate links area. But what about the embedded resources? Is there a way to generate the documentation for the field of the embedded resoure?

**Comment by jmisur** [comment]
Hi Viktor, what classes do you use for this? Custom POJOs with these fields or Spring-provided ones? 
It's definitely possible to accommodate this, but it's not straightforward. PRs are always welcome.

**Comment by kschulst** [comment]
As a workaround/hack, you could create your own custom class that inherits from `ResourceSupport`, and use this as base class for your spring-hateoas resources.

E.g.
```
/**
 * A spring-hateoas ResourceSupport that expand _links when used in conjunction with spring-auto-restdocs
 */
public class CustomResourceSupport extends ResourceSupport {

    /**
     * Hypermedia links
     */
    @Override
    @RestdocsNotExpanded
    public List<Link> getLinks() {
        return super.getLinks();
    }
}
```

And then, in your resource class, instead of:
```
public class SomeResource extends ResourceSupport {...}
```
...extend from you custom `ResourceSupport` class:
```
public class SomeResource extends CustomResourceSupport {...}
```
This would produce something like:
![image](https://user-images.githubusercontent.com/21902/42944028-dca86d7e-8b64-11e8-88c2-08a4e6644a06.png)

**Comment by viktorgt** [comment]
We are using the spring provided Resource classes, where we expand the Resource to be able of embedding resources.
```
public class HALResource<T> extends Resource<T> {
    private ResourceSupport embedded;

    @JsonInclude(Include.NON_EMPTY)
    @JsonUnwrapped
    public ResourceSupport getEmbedded() {
        return this.embedded;
    }
    ...
}
```
However, spring embeds collection by itself (using the Resources class as return type):
`public ResponseEntity<Resources<Pocket>> getPockets() { }`

Response body:
```
{
  "_embedded" : {
    "pockets" : [ {
      "id" : "1",
      "status" : "FINISHED",
      "packageId" : "myPackageId",
      "sequence" : 1,
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/api/pockets/1"
        },
        "pockets" : {
          "href" : "http://localhost:8080/api/packages"
        }
      }
    }, {
      "id" : "2",
      "status" : "FINISHED",
      "packageId" : "myPackageId",
      "sequence" : 2,
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/api/pockets/2"
        },
        "pockets" : {
          "href" : "http://localhost:8080/api/packages"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/api/packages"
    }
  }
}
```
![image](https://user-images.githubusercontent.com/484128/43021861-82b3e382-8c65-11e8-999b-3c2cd7a5b08b.png)

**Comment by viktorgt** [comment]
@kschulst thank you for the hint with the workaround. 
I favour a mechanism within the test setup of restdocs. We modified the AbstractJacksonFieldSnippet to make the resolving of FieldDescriptors configureable, but noting what would fit a pull request yet.

**Comment by kschulst** [comment]
An option could be to loosen up this method a bit:
https://github.com/ScaCap/spring-auto-restdocs/blob/431f76ef0e810a1b87df3361414b63ca344e9744/spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/jackson/FieldDocumentationObjectVisitor.java#L106-L108

with something like:
```
    private boolean shouldExpand(BeanProperty prop) {
        return prop.getMember().getAnnotation(RestdocsNotExpanded.class) == null
                && !SKIPPED_FIELDS.contains(prop.getName());
    }
```
Where SKIPPED_FIELDS would be something ala:
```
    private final static Set<String> SKIPPED_FIELDS = new HashSet<>(Arrays.asList("_links", "_embedded"));
```
(... and as a bonus:  also make it configurable for the user to add custom fields that will not be expanded.)

Is this what you have done, @viktorgt?

**Comment by viktorgt** [comment]
We changed AbstractJacksonFieldSnippet by extracting the resolveFieldDescriptors method into a new class:
```
public class FieldDescriptorResolver {

    public void resolve(Map<String, FieldDescriptor> fieldDescriptors,
                 Type type, ObjectMapper objectMapper, JavadocReader javadocReader,
                 ConstraintReader constraintReader) throws JsonMappingException {
        FieldDocumentationGenerator generator = new FieldDocumentationGenerator(
                objectMapper.writer(), objectMapper.getDeserializationConfig(), javadocReader,
                constraintReader);
        List<FieldDescriptor> descriptors = generator.generateDocumentation(type,
                objectMapper.getTypeFactory());
        for (FieldDescriptor descriptor : descriptors) {
            if(isRelevant(descriptor)) {
                fieldDescriptors.putIfAbsent(descriptor.getPath(), descriptor);
            }
        }
    }

    protected boolean isRelevant(FieldDescriptor descriptor) {
        return true;
    }
}
```
This allows to inject a custom resolver:
```
public class JacksonResponseFieldSnippet extends AbstractJacksonFieldSnippet {
...
    public JacksonResponseFieldSnippet dieldDescriptorResolver (FieldDescriptorResolver fieldDescriptorResolver) {
        return new JacksonResponseFieldSnippet(responseBodyType, failOnUndocumentedFields, fieldDescriptorResolver);
    }
} 
```

While your approach seems to be the right way to go.

**Comment by jmisur** [comment]
We'll collaborate on this PR to get this done #249 . Thanks a lot guys

**Comment by viktorgt** [comment]
One additional remark. Since the generated response fields do no match the actual json property names (links<>_links and content<>_embedded) it would be nice to provide a renaming pattern into the configuration.

**Comment by jmisur** [comment]
I've been looking into this a bit and I have one fundamental question: how to actually document links?

We obviously don't want to use spring-restdocs' verbose style, e.g. `linkWithRel(..)` on each test. We never rely on response from example, because that might be incomplete - we always use the response structure itself.

But in this case, links or embedded is generic Map without any structure that you can introspect and auto-document.

So I thought maybe we need to rethink this completely and somehow utilize Javadoc on a response class. What I invented is no rocket science, but could do and is very easy to integrate into the documentation generation process.
```
/**
 * Item attributes.
 * <p>
 *
 * @link rel=person; description=Related persons; optional=false
 * @link rel=children; description=Child items; deprecated=true
 */
class ItemResponse {
  ...
```

The `@link` tag contains arbitrary key=value pairs, which correspond with auto-links snippet (both tag keys and snippet content is therefore fully i18n-able and customizable).

```
{{#hasContent}}

|===
|{{th-rel}}|{{th-optional}}|{{th-description}}

{{#content}}
|{{rel}}
|{{optional}}
|{{description}}

{{/content}}
|==={{/hasContent}}{{#noContent}}{{no-links}}{{/noContent}}
```

**Comment by jmisur** [comment]
@viktorgt @kschulst what do you say to my proposal? Embedded and links are highly dynamic structures, which can depend on the internal state of the primary object. So I would not try to document them from examples.
Furthermore, Embedded structure is some resource which should be available from another endpoint and therefore we probably do not want to inline the full documentation of embedded, but only link to it's primary documentation location.

**Comment by kschulst** [comment]
In my project I have ended up combining vanilla spring restdocs links with spring auto restdocs to support documentation of hypermedia links. This means that I have to write the documentation for the different links in the tests instead of closer to the code.

Also, in order to support actual links between documentation, I ended up with a hack that uses raw asciidoc markup in the tests, like this:
```
mockMvc.perform(get("/producers"))
    .andExpect(status().isOk())
    .andDo(doc(links(
        linkWithRel("r:something").description("The root <<resources-something, Something resource>>")
)));
```

There are other issues I haven't yet addressed, like:
- include more info about the link, like method, params, etc. This kind of information needs be described in a unstructured manner in the description text. It would be nice to be able to present a "links table" that could include more information than just a `name` and `description` columns.
- some mechanism to decide if the hypermedia links should be included in the auto-section. To support this I have ended up with introducing an Annotation that controls which kind of section configuration to apply for each test. I could rework this a bit and share it if you would like.

*It sounds like an interesting approach to use the @link javadoc tag to document links instead!* If you want I'd be happy to look further into this along with you!

Would be nice if we support a way of generating asciidoc links to associated resources' docs. Maybe the link text can be a little bit smarter than just a simple text string, e.g. it could be something like:
```
@link my relation name|my relation description <a>LinkedResource</a>|another column
```
...which would result in a 3 columns table.

A HAL link can have fields like "method" and "title". If we detect these, the link description could include this information automatically.

**Comment by viktorgt** [comment]
Our approach to document the links is similar to what kschulst described. I really like the idea to document the links in javadoc.
Regarding the Embedded structure, currently we are using a hack to prevent the documentation of embededd fields. I would welcome it to not inline the full documentation of embedded but just have a link to it's actual documentation.

**Comment by jmisur** [comment]
Ok sounds good. I'll try to develop further the Javadoc approach, but with support for cross linking the target resources.

**Comment by jmisur** [comment]
Hi all, HATEOAS support (links and embedded) was implemented in 2.0.3-SNAPSHOT. Check the docs https://scacap.github.io/spring-auto-restdocs/#snippets-links and try it out if it works for you.

**Comment by viktorgt** [comment]
Great job, we appreciate your effort. The SNAPSHOT release works for us. 
The need for Documentation classes feels a little bit awkward, but I guess this comes with the generic stlye of HATEOAS. 
One question regarding the handling of resources collections. We are implementing collections endpoints in the following fashion:
`public ResponseEntity<Resources<StockRecordGroupResource>> getStockRecordGroups()`
Spring HATEOAS embedds such collection automatically:
```
{
  "_embedded" : {
    "stockRecordGroups" : [ {

      "stockRecordGroupId" : "97bebb1a-cbce-34e6-bfdf-edaf7d770ec0",
      "tsuId" : "3521881b-16ae-332a-9975-6d7f619c3f13",
      "sourceProcessAreaId" : "617918a6-b819-11e8-96f8-529269fb1459",
      "destinationProcessAreaId" : "85feef84-6991-46ac-b31c-48bc992cef9e"
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/stock-supplier/api/stock-record-groups/97bebb1a-cbce-34e6-bfdf-edaf7d770ec0"
        },
        "stock-record-groups" : {
          "href" : "http://localhost:8080/stock-supplier/api/stock-record-groups"
        }
      }
    }...
```
The response fields generated by auto-rest-docs still contain the attributes of the embeded Resource.
![image](https://user-images.githubusercontent.com/484128/48621443-d490ca80-e9a3-11e8-9f94-2f5f0e37e257.png)

I have noticed that you are implementing a HALResource in your example to embedd resources. Is this also required to get rid of the embedded attributes in the response fields?

**Comment by jmisur** [comment]
I have already in-progress PR #276 for `Resources` which would fix this by making response fields snippet empty and referring to embedded snippet for more details.

**Comment by jmisur** [comment]
You can try latest snapshot. Please let me know if it fixes the snippet for you.

**Comment by jmisur** [comment]
HATEOAS is supported, see [Links](https://scacap.github.io/spring-auto-restdocs/#snippets-links) and [Embedded](https://scacap.github.io/spring-auto-restdocs/#snippets-embedded) snippet support and [related examples](https://github.com/ScaCap/spring-auto-restdocs/blob/78ede3c72a3b61086ff3049d6abd93b8060f1202/samples/java-webmvc/src/main/java/capital/scalable/restdocs/example/items/ItemResource.java#L277).
