### ISSUE TITLE
Expand Map automatically

### ISSUE THREAD

**Issue by unlimitedsola** [ScaCap/spring-auto-restdocs#283]
for example:

If we have the following domain class:

```kotlin
data class Embedded(val foo:String, val bar:Int)
data class MyDomain(val name:String, val map:Map<String,Embedded>)
```

We can document `MyDomain` class with following json paths.

- name
- map.*.foo
- map.*.bar

It would be nice if `Map`s can be expanded because its possible to map the domain class above in JPA

**Comment by jmisur** [comment]
How is this currently shown with SARD? Would you like to submit a PR, at least with an example for us to see how it behaves?

**Comment by unlimitedsola** [comment]
> How is this currently shown with SARD? 

Currently, it only shows the documentation for the `map` property with the `type` being `Map`, neither its key nor value gets expanded.

>  Would you like to submit a PR, at least with an example for us to see how it behaves?

I'd like to submit a PR for this but unfortunately I'm busy at work at present.

What's your opinion for having following documenting entries in our fields table of `MyDomain` object above?

- `name`: for `MyDomain.name`
- `map`: for `MyDomain.map` also for documenting `key` part of the map if needed
- map.*.foo: for `Embedded.foo`
- map.*.bar: for `Embedded.bar`

these should cover all documentable locations for properties

**Comment by jmisur** [comment]
The reason why we didn't implement Map is because it's not possible to determine it's contents statically. It can contain different elements in different situations, therefore it is preferred to be documented manually (custom asciidoc) or you can use existing facilities which allows you to put a documentation class in place of the result. See [example](https://github.com/ScaCap/spring-auto-restdocs/blob/9ef5fab35e416fc69f4ba8f9c8d073ac148cf3b5/samples/java-webmvc/src/test/java/capital/scalable/restdocs/example/items/ItemResourceTest.java#L148) or documentation (https://scacap.github.io/spring-auto-restdocs/#_configuration_4).

**Comment by jmisur** [comment]
Closing because issue has a workaround.
