### ISSUE TITLE
Top level Javadoc not added in field description column

### ISSUE THREAD

**Issue by karlmuscat** [ScaCap/spring-auto-restdocs#301]
Referring to [your sample project](https://github.com/ScaCap/spring-auto-restdocs/tree/master/samples/java-webmvc)

I have noticed that the generated final HTML (`target/generated-docs/index.html`), the Javadoc descriptions for top level fields are not included.

I have also tried a fresh project, resulting in the same outcome.

![image](https://user-images.githubusercontent.com/12797180/54492038-6e6d7300-48c3-11e9-8757-b6c4fde4f21b.png)

![image](https://user-images.githubusercontent.com/12797180/54492028-5ac20c80-48c3-11e9-91dc-61541c0e2503.png)

**Comment by jmisur** [comment]
Did you generate it from latest master? Because I just checked and it works for me locally and you can also verify it in [published documentation](https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/samples/java-webmvc/generated-docs/index.html#resources-items-get) for java-webmvc sample.

**Comment by karlmuscat** [comment]
@jmisur I have further checked the issue, and found that the descriptions are omitted when the `maven-javadoc-plugin` is disabled. I had disabled it since it wasn't working with JDK11. What are my options?

**Comment by karlmuscat** [comment]
@jmisur I got this issue fixed from my end. For anyone stumbling here, Javadoc plugin is required and make sure JAVA_HOME is set to the correct version.

**Comment by jmisur** [comment]
Great, thanks!
