### ISSUE TITLE
multimodule project support

### ISSUE THREAD

**Issue by warmuuh** [ScaCap/spring-auto-restdocs#58]
i tried to apply this plugin to a project where the resources are in one project (A) and the domain-classes are in another project (B).

restdoc-tests are in A, so javadoc is only read for these classes. Is it possible to generate the stuff that goes into generated-javadoc-json for project B and have spring-auto-restdoc pick up generated-javadoc-json for both A and B?

**Comment by fbenz** [comment]
It might work for you if you modify your build process so that the following steps are executed:
1. Run the doclet in project B. The doclet is independent of the other parts and just generates JSON files.
2. Run the doclet in project A.
3. Copy the generated JSON files from project B to project A so that everything ends up in the same folder.
4. Run the tests in project A.

An alternative solution would be that we add support for multiple folders to `org.springframework.restdocs.javadocJsonDir`.

**Comment by fbenz** [comment]
Is this issue solved for you or do you still need support from our side?

**Comment by warmuuh** [comment]
I honestly hope for support of multiple paths because otherwise the whole build setup becomes too complicated. Sadly I don't have enough time to look into it by myself. If you don't implement that, you can close this issue...

**Comment by fbenz** [comment]
We just released version 1.0.6 that adds support for listing multiple directories.

**Comment by warmuuh** [comment]
Many Thanks. Will test it soon
