### ISSUE TITLE
JacksonRequestFieldSnippet/JacksonResponseFieldSnippet: add an option to limit the fields to what actual is in request/response

### ISSUE THREAD

**Issue by ddrozdov** [ScaCap/spring-auto-restdocs#64]
For example I have a model with `id` that is generated on the server. When a new model is POSTed there shouldn't be any `id` in it and I can configure ObjectMapper to skip null fields so that `id` is hidden in "Example request" section, but having it described in the "Request structure" section could be confusing for the reader.

**Comment by fbenz** [comment]
Your solution does not prevent the client from sending an ID. I guess that is ignored later, but it's up to the client whether it is null or not. I don't see what you gain by ignoring null fields when parsing JSON. The field on the POJO will be null anyway - or not if the client send a non-null value. When generating JSON out of a POJO it makes sense to ignore null fields so that they don't end up in the JSON object. Question is whether this is a good practice.

Currently, we generate the request and response structures out of the Java classes and don't access the actual value while doing this. Therefore, it would be a bigger effort to add support for this.

**Comment by jmisur** [comment]
@ddrozdov as Florian mentioned, we analyse actual classes to determine request/response fields and not the example values. If you want to hide the `id` from request fields, you can create a class hierarchy so that request does not contain id and response does.
