### ISSUE TITLE
Example project is not building

### ISSUE THREAD

**Issue by ugultopu** [ScaCap/spring-auto-restdocs#83]
I am getting the following error:

```
Error:(66, 0) Could not find capital.scalable:spring-auto-restdocs-json-doclet:1.0.6-SNAPSHOT.
Required by:
    capital.scalable:spring-auto-restdocs-example:1.0.6-SNAPSHOT
```
Am I missing something here?

Regards

**Comment by jmisur** [comment]
Did you try building everything from parent pom? `mvn install` from root directory.

**Comment by ugultopu** [comment]
No, I just imported the `build.gradle` under `spring-auto-restdocs-example` to my IDE. Do I have to `mvn install` from root directory as well? Isn't it enough to import the `build.gradle` under `spring-auto-restdocs-example` to my IDE?

**Comment by ugultopu** [comment]
I couldn't build Spring REST Docs `v1.1.2-RELEASE` as well. I am getting checkstyle errors and even if I disable checkstyle, I get many failed tests. I guess something is not right with my configuration but I am not sure what.

**Comment by fbenz** [comment]
Switching to the latest released version in `build.gradle` should fix the build for you.
Change
```
version = '1.0.6-SNAPSHOT'
```
found at https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-example/build.gradle#L20 to
```
version = '1.0.6'
```

The example should always point to the latest development version and thus usually requires you to build the whole project locally. However, we missed to update the version lately. This is fixed in https://github.com/ScaCap/spring-auto-restdocs/pull/84
