### ISSUE TITLE
Fail test when undocumented field

### ISSUE THREAD

**Issue by dacofr** [ScaCap/spring-auto-restdocs#91]
Hi,

 SpringRestDocs provide the capacity to fail test when fields are undocumented. 

Extract from thé documentation :

"When documenting fields, the test will fail if an undocumented field is found in the payload. Similarly, the test will also fail if a documented field is not found in the payload and the field has not been marked as optional"

Does SpringAutoRestDocs provides the same capacity when javadoc is missing ?

Thanks for your work.

**Comment by fbenz** [comment]
Spring Auto REST Docs does not have that feature and we have not thought about it yet. But it's an interesting idea. It shouldn't be enabled by default, but would be a nice feature hidden behind a flag. We are reading Javadoc on the method, the method parameters and the request and the response body. For an initial implementation it should be fine to fail if any of the comments are missing because it most cases you want all.

**Comment by dacofr** [comment]
Hi,

It's ok for me to fail if comments are missing.
Maybe it could an option in the doclet that parse the javadoc ?

OK to have a feature flag who is desactivated by default.

Any idea when this feature could be implémenter ?
